dist: xenial
language: python
git:
  depth: 50 # Need old commits for determining version of untagged builds
env: DJANGO=1.11
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.5 
    env: DJANGO=2.2
  - python: 3.6
    env: DJANGO=2.2
  - python: 3.7
    env: DJANGO=2.2
install:
  - pip install Django~=${DJANGO}.0
  - make bootstrap
script:
  - make test lint
deploy:
  provider: pypi
  user: calberto.cortez
  distributions: bdist_wheel sdist
  on:
    all_branches: true
    repo: opentracing-contrib/python-django
    tags: true
  password:
    secure: T6bZrINIEbGVtuOz9Z0orWvsEG75owxVG38oO0PF+3hzTt7At3j9duoWerTlavnvnBogf9y0Q+lWE91RtJYkAfjVxCxob0fih/sfuXanlXMj+2eUZe4/jW4XqM8nRoW6/lw5zj/MLoE/fa+duK+PYRYe8vMJJpQvPfGlrJ5qKIS0EwRI2v3ISjjDhN2VXl2V1tuWSPDaZMSuJW5B2JYtNUY7dZqeRhr1icDV0qHeEGcvK8Rlxmy5WGBmzlKnvha6e0NV7t0BSCVw21q7VUnrEC+SCAqmOo12HIHQ6WCcDE4m6cFjM3LK9iFmWivmFBLLBqlQNZLH5wB8wg9cemCqMxvsNwb3hX3Iqn/ps/JBxU+d/HgTLrN0o77RN8b2sA8yLpWL2CqTV8dECbDAAKZpa0Mg/OqQA3iFNuoXvsd0oxW2TFWRFN7RmHvDHcPVtwu+MpP1fCi1F8DZM7bibH8VX/jIbsN11yXbdBvJZNBlP/ZTlOD16PqAv3fVve6Zk4oF0Ur7BrqiGF+X8dTR64cPOToojFQTm7eQvM3pLbTnCAG1bR41Qw5VIh8OFwq3eYn1WRHtu2qFMgRinz9G+3okuAHQGOWu7fuKjdEdnHdecurPzkTegXlF7xXBXOrp/wSXErO7muBdSRoU71SiNgPwjNvq8dfLSlcwNHVKdjXW6HM=
